POST http://localhost:8080/account
content-type: application/json

{
    "accountNumber": "33333",
    "customerId": 1
}

###
GET http://localhost:8080/customer/1
Accept: application/json

###
GET http://localhost:8080/customers
Accept: application/json

###
DELETE http://localhost:8080/customer/1
